mod engine;
mod tcp_syn_crafter;

use clap::Parser;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};
use std::process::Command;
use tokio::time::{sleep, Duration};
use tokio::sync::Semaphore;
use nix::ifaddrs::getifaddrs;
use nix::net::if_::InterfaceFlags;

use aya::{Ebpf, programs::{Xdp, XdpFlags}, maps::perf::AsyncPerfEventArray, util::online_cpus};
use bytes::BytesMut;

#[repr(C, align(8))]
#[derive(Clone, Copy)]
pub struct PacketInfo {
    pub src_addr: [u32; 4],
    pub dst_addr: [u32; 4],
    pub protocol: u32,
    pub version: u32,
}

#[derive(Parser)]
#[command(name = "zerotrace", about = "Universal Stealth Shield")]
struct Cli {
    #[arg(short, long)] quiet: bool,
    #[arg(short, long)] remove: bool,
}

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let args = Cli::parse();
    if let Err(_) = rlimit::setrlimit(rlimit::Resource::MEMLOCK, rlimit::INFINITY, rlimit::INFINITY) {}

    let running = Arc::new(AtomicBool::new(true));
    let r = running.clone();
    ctrlc::set_handler(move || { r.store(false, Ordering::SeqCst); })?;

    let mut interfaces = Vec::new();
    if let Ok(addrs) = getifaddrs() {
        for ifaddr in addrs {
            let name = ifaddr.interface_name;
            if !ifaddr.flags.contains(InterfaceFlags::IFF_LOOPBACK) && ifaddr.address.is_some() {
                if !interfaces.contains(&name) {
                    interfaces.push(name.clone());
                    let _ = Command::new("ip").args(["link", "set", "dev", &name, "xdp", "off"]).output();
                }
            }
        }
    }

    if args.remove {
        engine::log_event("EXIT", "ZeroTrace Shields detached.", false);
        return Ok(());
    }

    engine::log_event("BOOT", "ZeroTrace Active: Universal Global Mode (v4/v6)", args.quiet);

    // Load the BPF object generated by build.rs
    let bpf_bytes = include_bytes!(concat!(env!("OUT_DIR"), "/interceptor.o"));
    let mut bpf = Ebpf::load(bpf_bytes)?;
    let program: &mut Xdp = bpf.program_mut("xdp_mutate").unwrap().try_into()?;
    program.load()?;

    for iface in interfaces.clone() {
        if let Err(e) = program.attach(&iface, XdpFlags::SKB_MODE) {
            engine::log_event("CRIT", &format!("Could not attach to {}: {}", iface, e), args.quiet);
        }
    }

    let engine = Arc::new(engine::StealthEngine::new(500_000));
    let task_semaphore = Arc::new(Semaphore::new(2000));
    let cpus = online_cpus()?;
    let mut perf_array = AsyncPerfEventArray::try_from(bpf.take_map("PACKET_EVENTS").unwrap())?;

    for cpu_id in cpus {
        let mut buf = perf_array.open(cpu_id, Some(32))?;
        let engine_local = engine.clone();
        let sem_local = task_semaphore.clone();
        let quiet = args.quiet;

        tokio::spawn(async move {
            let mut buffers = (0..10).map(|_| BytesMut::with_capacity(128)).collect::<Vec<_>>();
            while let Ok(events) = buf.read_events(&mut buffers).await {
                for i in 0..events.read {
                    if buffers[i].len() < std::mem::size_of::<PacketInfo>() { continue; }
                    let info = unsafe { &*(buffers[i].as_ptr() as *const PacketInfo) };
                    
                    let dst_ip = if info.version == 4 {
                        IpAddr::V4(Ipv4Addr::from(info.dst_addr[0].to_be()))
                    } else if info.version == 6 {
                        let mut segments = [0u8; 16];
                        for j in 0..4 {
                            segments[j*4..(j+1)*4].copy_from_slice(&info.dst_addr[j].to_ne_bytes());
                        }
                        IpAddr::V6(Ipv6Addr::from(segments))
                    } else {
                        continue;
                    };

                    if let Ok(permit) = sem_local.clone().try_acquire_owned() {
                        let engine_task = engine_local.clone();
                        tokio::task::spawn_blocking(move || {
                            let _ = engine_task.dispatch_stealth_sequence(dst_ip);
                            drop(permit);
                        });
                        engine::log_event("BYPASS", &format!("Masking: {}", dst_ip), quiet);
                    }
                }
            }
        });
    }

    while running.load(Ordering::SeqCst) { sleep(Duration::from_millis(100)).await; }

    engine::log_event("EXIT", "Detaching BPF programs and cleaning interfaces...", false);
    for iface in interfaces {
        let _ = Command::new("ip").args(["link", "set", "dev", &iface, "xdp", "off"]).output();
    }
    std::process::exit(0);
}
